/**
 * @file assem.h
 * @brief Assembly instruction representation for the Tiger compiler
 *
 * This file defines the abstract assembly instruction types used between
 * code generation and register allocation.  Instructions use a symbolic
 * operand notation (`s0, `s1, `d0, `d1, …) that is resolved to physical
 * register names after register allocation.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * Instruction types
 * ─────────────────────────────────────────────────────────────────────────
 *
 *   OperInstr  – a general operation (arithmetic, memory, jump, call, …)
 *                Has explicit Def (destination) and Use (source) temp lists,
 *                and an optional Targets list for jump instructions.
 *
 *   LabelInstr – an assembly label definition (e.g., "L3:")
 *                Defines no temps and uses no temps.
 *
 *   MoveInstr  – a register-to-register move ("movq `s0, `d0")
 *                Treated specially by the register allocator: if source and
 *                destination are assigned the same color, the move is deleted.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * Operand notation in assembly strings
 * ─────────────────────────────────────────────────────────────────────────
 * Assembly strings use backtick placeholders:
 *   `s0, `s1, …  – source (Use) temporaries, in order
 *   `d0, `d1, …  – destination (Def) temporaries, in order
 *
 * When printing, each placeholder is replaced by the register name from
 * the provided temp::Map (e.g., "`s0" → "%rax").
 *
 * ─────────────────────────────────────────────────────────────────────────
 * InstrList
 * ─────────────────────────────────────────────────────────────────────────
 * An ordered list of Instr* objects representing the instruction stream
 * for one function body.  Supports insertion, deletion, and replacement
 * (used during spill rewriting in register allocation).
 *
 * ─────────────────────────────────────────────────────────────────────────
 * Proc
 * ─────────────────────────────────────────────────────────────────────────
 * Wraps a function's instruction list with its prologue and epilogue
 * strings (generated by ProcEntryExit3).
 */

#ifndef TIGER_CODEGEN_ASSEM_H_
#define TIGER_CODEGEN_ASSEM_H_

#include <cstdio>
#include <string>
#include <vector>

#include "tiger/frame/temp.h"

namespace assem {

/**
 * @brief Jump target list for branch instructions
 *
 * Holds the set of possible target labels for a jump or conditional branch.
 * Used by liveness analysis and the flow graph to determine control flow edges.
 */
class Targets {
public:
  std::vector<temp::Label *> *labels_; ///< Possible jump targets

  explicit Targets(std::vector<temp::Label *> *labels) : labels_(labels) {}
};

/**
 * @brief Abstract base class for assembly instructions
 *
 * Every instruction has:
 *   - Print(): emit the instruction with register names substituted
 *   - Def():   the set of temporaries written (defined) by this instruction
 *   - Use():   the set of temporaries read (used) by this instruction
 *
 * Def/Use information is used by liveness analysis to compute live-in and
 * live-out sets, and by the register allocator to build the interference graph.
 */
class Instr {
public:
  virtual ~Instr() = default;

  /**
   * @brief Print the instruction with register names from @p m
   * @param out Output file
   * @param m   Temp-to-register-name map (from register allocation)
   */
  virtual void Print(FILE *out, temp::Map *m) const = 0;

  /**
   * @brief Get the temporaries defined (written) by this instruction
   * @return TempList of defined temporaries (may be empty)
   */
  [[nodiscard]] virtual temp::TempList *Def() const = 0;

  /**
   * @brief Get the temporaries used (read) by this instruction
   * @return TempList of used temporaries (may be empty)
   */
  [[nodiscard]] virtual temp::TempList *Use() const = 0;
};

/**
 * @brief A general assembly operation instruction
 *
 * Represents any instruction that is not a pure register move or label:
 * arithmetic, memory access, call, jump, conditional branch, etc.
 *
 * The assembly string uses backtick notation:
 *   `s0, `s1, … for source (Use) registers
 *   `d0, `d1, … for destination (Def) registers
 *
 * If jumps_ is non-null, this is a branch instruction and the flow graph
 * will add edges to all listed target labels.
 */
class OperInstr : public Instr {
public:
  std::string assem_;       ///< Assembly template string (with `s/`d placeholders)
  temp::TempList *dst_;     ///< Defined (destination) temporaries
  temp::TempList *src_;     ///< Used (source) temporaries
  Targets *jumps_;          ///< Jump targets (nullptr for non-branch instructions)

  OperInstr(std::string assem, temp::TempList *dst, temp::TempList *src,
            Targets *jumps)
      : assem_(std::move(assem)), dst_(dst), src_(src), jumps_(jumps) {}

  void Print(FILE *out, temp::Map *m) const override;
  [[nodiscard]] temp::TempList *Def() const override;
  [[nodiscard]] temp::TempList *Use() const override;
};

/**
 * @brief An assembly label definition
 *
 * Represents a label at the current position in the instruction stream,
 * e.g., "L3:" or "tigermain:".
 *
 * Labels define no temporaries and use no temporaries.  They are used as
 * jump targets and as function entry points.
 */
class LabelInstr : public Instr {
public:
  std::string assem_;    ///< Assembly string (e.g., "L3:")
  temp::Label *label_;   ///< The label being defined (for flow graph construction)

  LabelInstr(std::string assem, temp::Label *label)
      : assem_(std::move(assem)), label_(label) {}

  void Print(FILE *out, temp::Map *m) const override;
  [[nodiscard]] temp::TempList *Def() const override;
  [[nodiscard]] temp::TempList *Use() const override;
};

/**
 * @brief A register-to-register move instruction
 *
 * Represents "movq `s0, `d0" – a copy from one register to another.
 *
 * MoveInstr is distinguished from OperInstr so that the register allocator
 * can identify move-related pairs for coalescing.  If the source and
 * destination are assigned the same physical register, the move is deleted.
 */
class MoveInstr : public Instr {
public:
  std::string assem_;    ///< Assembly template (usually "movq `s0, `d0")
  temp::TempList *dst_;  ///< Destination temporary (exactly one)
  temp::TempList *src_;  ///< Source temporary (exactly one)

  MoveInstr(std::string assem, temp::TempList *dst, temp::TempList *src)
      : assem_(std::move(assem)), dst_(dst), src_(src) {}

  void Print(FILE *out, temp::Map *m) const override;
  [[nodiscard]] temp::TempList *Def() const override;
  [[nodiscard]] temp::TempList *Use() const override;
};

/**
 * @brief An ordered list of assembly instructions
 *
 * Represents the instruction stream for one function body.
 * Supports append, remove, insert, and replace operations used during
 * spill rewriting in register allocation.
 */
class InstrList {
public:
  InstrList() = default;

  /** @brief Print all instructions with register names from @p m */
  void Print(FILE *out, temp::Map *m) const;

  /** @brief Append an instruction to the end of the list */
  void Append(assem::Instr *instr) { instr_list_.push_back(instr); }

  /** @brief Remove the first occurrence of @p instr from the list */
  void Remove(assem::Instr *instr) { instr_list_.remove(instr); }

  /** @brief Erase the instruction at position @p pos */
  void Erase(std::list<Instr *>::const_iterator pos) { instr_list_.erase(pos); }

  /** @brief Insert @p instr before position @p pos */
  void Insert(std::list<Instr *>::const_iterator pos, assem::Instr *instr) {
    instr_list_.insert(pos, instr);
  }

  /**
   * @brief Replace the instruction at @p pos with @p instr
   * @return Iterator pointing to the newly inserted instruction
   */
  std::list<Instr *>::const_iterator Replace(
    std::list<Instr *>::const_iterator pos, assem::Instr *instr) {
    instr_list_.insert(pos, instr);
    pos = instr_list_.erase(pos);
    pos--;
    return pos;
  }

  /** @brief Get the underlying instruction list */
  [[nodiscard]] const std::list<Instr *> &GetList() const {
    return instr_list_;
  }

private:
  std::list<Instr *> instr_list_;
};

/**
 * @brief A complete compiled function: prologue + body + epilogue
 *
 * Produced by ProcEntryExit3.  The prologue and epilogue are plain strings
 * (already fully resolved assembly), while the body is an InstrList that
 * still uses temp::Map for register name resolution.
 */
class Proc {
public:
  std::string prolog_;   ///< Function prologue (label, stack allocation)
  InstrList *body_;      ///< Function body instructions
  std::string epilog_;   ///< Function epilogue (stack deallocation, retq)

  Proc(std::string prolog, InstrList *body, std::string epilog)
      : prolog_(std::move(prolog)), body_(body), epilog_(std::move(epilog)) {}
};

/**
 * @brief A memory operand descriptor for code generation
 *
 * Used internally by the Munch() methods to represent a memory address
 * operand (e.g., "8(%rax)") together with the base register(s) it uses.
 * This allows the code generator to emit correct Def/Use lists for
 * memory-referencing instructions.
 */
class MemFetch {
public:
  std::string fetch_;    ///< Assembly operand string (e.g., "8(`s1)")
  temp::TempList *regs_; ///< Base/index registers used in the address

  MemFetch() { regs_ = new temp::TempList(); }
  MemFetch(std::string fetch, temp::TempList *regs)
    : fetch_(fetch), regs_(regs) {}
};

} // namespace assem

#endif // TIGER_CODEGEN_ASSEM_H_
